version: '3'
services:
  postgres:
    image: postgres:11.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: santa
      POSTGRES_PASSWORD: example
      POSTGRES_DATABASE: santa
  loadbalancer:
    image: openresty/openresty
    ports:
      - "9000:80"
    volumes:
      - "./nginx-dev.conf:/etc/nginx/conf.d/default.conf"