santa:
  url: https://santa.hejcz.usermd.net
spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://pgsql55.mydevil.net:5432/p1030_loteria
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  mail:
    host: mail55.mydevil.net
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
    test-connection: true
    username: ${EMAIL_USER}
    password: ${EMAIL_PASSWORD}
server:
  forward-headers-strategy: native