santa:
  url: http://localhost:9000
spring:
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:postgresql:santa
    username: santa
    password: example
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
  data:
    rest:
      detection-strategy: ANNOTATED
      base-path: /api
server:
  forward-headers-strategy: native