santa:
  url: https://meet-your-santa.herokuapp.com
spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  data:
    rest:
      detection-strategy: ANNOTATED
      base-path: /api
  datasource:
    url: ${JDBC_DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.mail.yahoo.com
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
    test-connection: true
    username: meet_your_santa@yahoo.com
    password: ${email.password}
server:
  forward-headers-strategy: native