santa:
  url: http://localhost:9000
spring:
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql:santa
    username: santa
    password: example
    initialization-mode: always
    driver-class-name: org.postgresql.Driver